language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

# Use fast travis build infrastructure explicitly
sudo: false
dist: trusty

# Installation installs dependencies
install:
  - pip install pytz
  - pip install .

script: cd tests && python -bb test_serpent.py
