# Use fast travis build infrastructure explicitly
sudo: false
dist: xenial

matrix:
  include:
    - language: python
      python: 3.8-dev
      install: pip install pytz attrs .
      script: cd tests && python -E -Wall -tt -bb test_serpent.py

    - language: python
      python: 3.7
      install: pip install pytz attrs .
      script: cd tests && python -E -Wall -tt -bb test_serpent.py

    - language: python
      python: 3.6
      install: pip install pytz attrs .
      script: cd tests && python -E -Wall -tt -bb test_serpent.py

    - language: python
      python: 3.5
      install: pip install pytz attrs .
      script: cd tests && python -E -Wall -tt -bb test_serpent.py

    - language: python
      python: 3.4
      install: pip install pytz attrs .
      script: cd tests && python -E -Wall -tt -bb test_serpent.py

    - language: python
      python: 2.7
      install: pip install pytz attrs enum34.
      script: cd tests && python -E -Wall -tt -bb test_serpent.py

    - language: python
      python: pypy3.5
      install: pip install pytz attrs .
      script: cd tests && python -E -Wall -bb test_serpent.py

    - language: java
      # jdk:
      #  - oraclejdk8
      script: mvn -f java/pom.xml verify
      cache:
        directories:
          - '$HOME/.m2/repository'

    - language: csharp
      mono: none
      dotnet: 2.2
      script: dotnet test dotnet/Serpent/Tests
