# Use fast travis build infrastructure explicitly
sudo: false
dist: xenial

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8-dev
    - python: pypy3.5

      # Installation installs dependencies
      install:
        - pip install pytz 'enum34;python_version<"3.4"' attrs .

      script:
        - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then cd tests && python -E -Wall -tt -bb test_serpent.py; fi
        - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then cd tests && python -E -Wall -bb test_serpent.py; fi
      # pypy doesn't like -tt option

    - language: java
      # jdk:
      #  - oraclejdk8
      sudo: false
      dist: trusty
      script: mvn -f java/pom.xml verify
      cache:
        directories:
          - '$HOME/.m2/repository'

    - language: csharp
      mono: none
      dist: xenial
      dotnet: 2.2
      script: dotnet test dotnet/Serpent/Tests

